server:
  port: 9050
  servlet.context-path: /account

spring:
  datasource:
    url: jdbc:postgresql://localhost:9010/codeforge-account-db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

stripe:
  api:
    secret: sk_test_51TOERJQr1RnoALfpqF9wL4klGnLFTTlxU6jJOKK4WeZtJeaSSGjm83bWzXzWAdIS61gEegOFfuM93DQFVQkR0Zdo00Vhe7yT6p
  webhook:
    secret: whsec_2dc50df58bbd417b008671285da17a36296c432a02f1eec3e664ec2333dcbb70
